### ISSUE TITLE
Send data over nfc to ios using ndef protocol

### ISSUE THREAD

**Issue by aminvb12** [justinribeiro/android-hostcardemulation-sample#1]
Hi,
First of All Thanks for your useful library.
I've got problem sending data over nfc to ios using ndef protocol.
I developed ios app as NFC Reader and I'm going to develope android app with HCE service which has the capability to send data (write data) for ios NFC Reader.
I've tried my ios Nfc Reader with some Android Card emulator app in playstore .they work fine but when I try your library as  an Android card emulator , Something is not detected by the ios Nfc Reader app.
I'll be very thankful if you can help me to solve my problem.

**Comment by karris7** [comment]
did you solve this?

**Comment by justinribeiro** [comment]
I'm in the process of bringing this example up-to-date (which I do every couple years). To answer that question, this app is useing HCE to emulate a type 4/ISO14443, not a type 2. This means you need to invoke the usual succession of commands (APDU, CC, et cetera). On iOS, I you can accomplish this with NFCISO7816Tag interface, setting the readerSession to iso14443, and then going through the usual steps (same as in the C example I have).

I don't have an iOS device on my desk at the moment, but I'll see about getting to an authoring an example of that. :+1:
